### ISSUE TITLE
更新日のフォーマットが読みづらい

### ISSUE THREAD

**Issue by munierujp** [javascript-tutorial/ja.javascript.info#313]
現在、更新日は「2日 一月 2021」のようなフォーマットなっています。

<img width="833" alt="スクリーンショット 2022-04-12 16 40 29" src="https://user-images.githubusercontent.com/20086673/162907152-d248d2ee-bf7d-4ac2-99c8-b494dc1c58b9.png">

このフォーマットは、以下の理由で読みづらいものです。

- アラビア数字と漢数字が混在している
- 順序が日月年になっている（年月日になっていない）[^1]

したがって、以下のいずれかのフォーマットにするのがいいかと思います。

1. 2021-01-02（`yyy-MM-dd`）
    - [ISO 8601](https://ja.wikipedia.org/wiki/ISO_8601)の拡張形式
2. 2021/1/2（`yyyy/M/d`）
    -  JSの[Date.toLocaleDateString('ja-JP')](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)のフォーマット
3. 2021年1月2日（`yyyy年M月d日`）
    - [GitHub](https://github.com/)、[MDN Web Docs](https://developer.mozilla.org/ja/)、[TypeScriptの公式ドキュメント](https://www.typescriptlang.org/ja/)などで用いられているフォーマット

私の意見では、人間が読むドキュメントに記載する日付の表記としては 3 がいいのではないかと思います。

これは、私にとってそうというだけの可能性もありますが、多くの日本人にとってもあてはまるであろうと思われます。

[^1]: https://ja.wikipedia.org/wiki/%E6%97%A5%E4%BB%98#%E5%B9%B4%E6%9C%88%E6%97%A5%E3%81%AE%E9%A0%86%E5%BA%8F%E3%81%AE%E6%B7%B7%E4%B9%B1

**Comment by KenjiI** [comment]
ありがとうございます。可読性・他サイトでの実績含め3 良いと思います。
該当箇所は、本リポジトリではなく公開用の別のリポジトリの内容と思われるため、そちらで対応いただけるよう話してみます。

**Comment by munierujp** [comment]
>該当箇所は、本リポジトリではなく公開用の別のリポジトリの内容と思われるため、そちらで対応いただけるよう話してみます。

そうだったのですね。
お手数おかけしますが、よろしくお願いします。

**Comment by KenjiI** [comment]
修正いただけました！

**Comment by munierujp** [comment]
@KenjiI ありがとうございました 😄
