### ISSUE TITLE
event.whichは非推奨

### ISSUE THREAD

**Issue by querykuma** [javascript-tutorial/ja.javascript.info#317]
日本語版の[ボタンを取得する: which](https://ja.javascript.info/mouse-events-basics#ref-787)で

> event.which == 1 – 左ボタン

という説明があるが、英語版の[Mouse button](https://javascript.info/mouse-events-basics#mouse-button)では

> As of now, event.which is deprecated, we shouldn’t use it.

という説明があり、event.buttonの使用を推奨する説明になっていると思います。

**Comment by KenjiI** [comment]
ありがとうございます！
該当のページ、最新の情報に更新しました。
https://github.com/javascript-tutorial/ja.javascript.info/commit/7a5c0e782a4023aa53251cbc40e4d28e7953fdcb

**Comment by querykuma** [comment]
ありがとうございます。
event.buttonの使用を推奨する説明になりました。
