### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ja.javascript.info#78]
Hi,

I renamed some stuff in 1-js/5-network and 1-js/11-async.

As a side effect, when you pull from upstream (from English version), git doesn't always recognize the renaming, and creates both English and Japanese versions, e.g.

1-js/11-async/05-async-await - old name (Japanese)
1-js/11-async/08-async-await - new name (English)
Please, remove 1-js/11-async/08-async-await. Instead, rename 1-js/11-async/05-async-await to 1-js/11-async/08-async-await, and adapt latest English changes to it.

P.S. Similar thing may happen with url chapter in networking when you next time pull upstream.

**Comment by KenjiI** [comment]
Sorry for replying late. I've addressed these changes.
